//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UELocalizationsTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UELocalizationsTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_ClearList {
            get {
                return ResourceManager.GetString("Btn_ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_FindNext {
            get {
                return ResourceManager.GetString("Btn_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_FindPrevious {
            get {
                return ResourceManager.GetString("Btn_FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_OK {
            get {
                return ResourceManager.GetString("Btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_RemoveSelected {
            get {
                return ResourceManager.GetString("Btn_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Replace {
            get {
                return ResourceManager.GetString("Btn_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Case Sensitive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckBox_MatchCase {
            get {
                return ResourceManager.GetString("CheckBox_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckBox_RegExp {
            get {
                return ResourceManager.GetString("CheckBox_RegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reverse Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckBox_ReverseMode {
            get {
                return ResourceManager.GetString("CheckBox_ReverseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColHeader_RowIndex {
            get {
                return ResourceManager.GetString("ColHeader_RowIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColHeader_Text {
            get {
                return ResourceManager.GetString("ColHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV File|*.csv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_Csv {
            get {
                return ResourceManager.GetString("Filter_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locres File|*.locres に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_Locres {
            get {
                return ResourceManager.GetString("Filter_Locres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locres File|*.locres に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_LocresMulti {
            get {
                return ResourceManager.GetString("Filter_LocresMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Localization Files|*.uasset;*.locres;*.umap|Uasset Files|*.uasset|Locres Files|*.locres|Umap Files|*.umap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_OpenFileDialogOfLocalization {
            get {
                return ResourceManager.GetString("Filter_OpenFileDialogOfLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text File|*.txt;*.csv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_OpenFileDialogTextOrCsv {
            get {
                return ResourceManager.GetString("Filter_OpenFileDialogTextOrCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text File|*.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_SaveFileDialogToExportText {
            get {
                return ResourceManager.GetString("Filter_SaveFileDialogToExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text File|*.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_Text {
            get {
                return ResourceManager.GetString("Filter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uasset File|*.uasset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_Uasset {
            get {
                return ResourceManager.GetString("Filter_Uasset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uasset/Umap File|*.uasset;*.umap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_UassetOrUmap {
            get {
                return ResourceManager.GetString("Filter_UassetOrUmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Umap File|*.umap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_Umap {
            get {
                return ResourceManager.GetString("Filter_Umap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Useful Tool for Editing Text in Unreal Engine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Description {
            get {
                return ResourceManager.GetString("Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_Column {
            get {
                return ResourceManager.GetString("Lbl_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of rows: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_DataCount {
            get {
                return ResourceManager.GetString("Lbl_DataCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Filtering に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_DataFiltering {
            get {
                return ResourceManager.GetString("Lbl_DataFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_EntryEditor {
            get {
                return ResourceManager.GetString("Lbl_EntryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External ID (.locres v4 only) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_ExternIDLocresV4Only {
            get {
                return ResourceManager.GetString("Lbl_ExternIDLocresV4Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_Filter {
            get {
                return ResourceManager.GetString("Lbl_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_FindAll {
            get {
                return ResourceManager.GetString("Lbl_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID Hash に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_IDHash {
            get {
                return ResourceManager.GetString("Lbl_IDHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_Input {
            get {
                return ResourceManager.GetString("Lbl_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Namespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_Namespace {
            get {
                return ResourceManager.GetString("Lbl_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Namespace Hash に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_NamespaceHash {
            get {
                return ResourceManager.GetString("Lbl_NamespaceHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of matches: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_NumOfMatches {
            get {
                return ResourceManager.GetString("Lbl_NumOfMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of replacements: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_NumOfReplaced {
            get {
                return ResourceManager.GetString("Lbl_NumOfReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_Replace {
            get {
                return ResourceManager.GetString("Lbl_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_ReplaceAll {
            get {
                return ResourceManager.GetString("Lbl_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_Search {
            get {
                return ResourceManager.GetString("Lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_Text {
            get {
                return ResourceManager.GetString("Lbl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Hash に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_TextHash {
            get {
                return ResourceManager.GetString("Lbl_TextHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lbl_VersionInfo {
            get {
                return ResourceManager.GetString("Lbl_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About the Program に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_AddRow {
            get {
                return ResourceManager.GetString("Menu_AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ascending (A-Z) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_AscendingA2Z {
            get {
                return ResourceManager.GetString("Menu_AscendingA2Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_CancelFilter {
            get {
                return ResourceManager.GetString("Menu_CancelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLI Commands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_CLIList {
            get {
                return ResourceManager.GetString("Menu_CLIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark Theme (Caution) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_DarkModeCareful {
            get {
                return ResourceManager.GetString("Menu_DarkModeCareful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Selected Rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_DeleteSelectedRows {
            get {
                return ResourceManager.GetString("Menu_DeleteSelectedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Descending (Z-A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_DescendingZ2A {
            get {
                return ResourceManager.GetString("Menu_DescendingZ2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Selected Rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_EditSelectedRows {
            get {
                return ResourceManager.GetString("Menu_EditSelectedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Filter {
            get {
                return ResourceManager.GetString("Menu_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font and Text Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_FontAndTextSize {
            get {
                return ResourceManager.GetString("Menu_FontAndTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_IDOrder {
            get {
                return ResourceManager.GetString("Menu_IDOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import by Row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_ImportByRowOrder {
            get {
                return ResourceManager.GetString("Menu_ImportByRowOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import CSV by ID (Slow) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_ImportCsvByIDSlow {
            get {
                return ResourceManager.GetString("Menu_ImportCsvByIDSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import New Row from CSV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_ImportRowsFromCsv {
            get {
                return ResourceManager.GetString("Menu_ImportRowsFromCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import TXT by ID (Slow) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_ImportTxtByIDSlow {
            get {
                return ResourceManager.GetString("Menu_ImportTxtByIDSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge Multiple Locations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_MergeLocres {
            get {
                return ResourceManager.GetString("Menu_MergeLocres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge Multiple Locations (Working) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_MergeLocresWorking {
            get {
                return ResourceManager.GetString("Menu_MergeLocresWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge Multiple UAssets (Beta) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_MergeUassetBeta {
            get {
                return ResourceManager.GetString("Menu_MergeUassetBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Actions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Operations {
            get {
                return ResourceManager.GetString("Menu_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Replace {
            get {
                return ResourceManager.GetString("Menu_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Sort {
            get {
                return ResourceManager.GetString("Menu_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support for .uasset/.umap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_SupportUassetOrUmap {
            get {
                return ResourceManager.GetString("Menu_SupportUassetOrUmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_TextOrder {
            get {
                return ResourceManager.GetString("Menu_TextOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Migrate Hash from Source Locres に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_TransferTextHashFromOriginalLocres {
            get {
                return ResourceManager.GetString("Menu_TransferTextHashFromOriginalLocres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TXT (No ID) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_TxtWithoutID {
            get {
                return ResourceManager.GetString("Menu_TxtWithoutID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text search or replace field cannot be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CannotBeEmptySearchTextOrReplaceFields {
            get {
                return ResourceManager.GetString("Msg_CannotBeEmptySearchTextOrReplaceFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to Load File: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CannotReadFile {
            get {
                return ResourceManager.GetString("Msg_CannotReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to write file! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CannotWriteFile {
            get {
                return ResourceManager.GetString("Msg_CannotWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A new row was added successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToAddRow {
            get {
                return ResourceManager.GetString("Msg_CompleteToAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The row was edited successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToEditRow {
            get {
                return ResourceManager.GetString("Msg_CompleteToEditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export successful! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToExport {
            get {
                return ResourceManager.GetString("Msg_CompleteToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exported successfully! \nPlease apply the same filter before importing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToExportAndBeforeImport {
            get {
                return ResourceManager.GetString("Msg_CompleteToExportAndBeforeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locres file hashes have been migrated successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToForwardTextHash {
            get {
                return ResourceManager.GetString("Msg_CompleteToForwardTextHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import successful! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToImport {
            get {
                return ResourceManager.GetString("Msg_CompleteToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import successful! \nPlease apply the same filter before importing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToImportAndBeforeImport {
            get {
                return ResourceManager.GetString("Msg_CompleteToImportAndBeforeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import successful by ID! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToImportByID {
            get {
                return ResourceManager.GetString("Msg_CompleteToImportByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New rows successfully imported! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToImportRows {
            get {
                return ResourceManager.GetString("Msg_CompleteToImportRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locres file(s) merged successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToMergeLocresFiles {
            get {
                return ResourceManager.GetString("Msg_CompleteToMergeLocresFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uasset file(s) merged successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToMergeUassetFiles {
            get {
                return ResourceManager.GetString("Msg_CompleteToMergeUassetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving successful. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompleteToSaveFile {
            get {
                return ResourceManager.GetString("Msg_CompleteToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the selected rows? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ConfirmToDeleteSelectedRows {
            get {
                return ResourceManager.GetString("Msg_ConfirmToDeleteSelectedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while adding the row:\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ErrorForAddRow {
            get {
                return ResourceManager.GetString("Msg_ErrorForAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while editing the row:\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ErrorForEditRow {
            get {
                return ResourceManager.GetString("Msg_ErrorForEditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while migrating .locres hashes:\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ErrorForForwardTextHash {
            get {
                return ResourceManager.GetString("Msg_ErrorForForwardTextHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while merging locres file(s):\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ErrorForMergeLocresFiles {
            get {
                return ResourceManager.GetString("Msg_ErrorForMergeLocresFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while merging uasset file(s):\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ErrorForMergeUassetFiles {
            get {
                return ResourceManager.GetString("Msg_ErrorForMergeUassetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Loading File: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ErrorForReadFile {
            get {
                return ResourceManager.GetString("Msg_ErrorForReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create export file! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_FailedToExport {
            get {
                return ResourceManager.GetString("Msg_FailedToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transferring text hashes. Please wait. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ForwardingTextHash {
            get {
                return ResourceManager.GetString("Msg_ForwardingTextHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merging locres. Please wait. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MergeLocressFiles {
            get {
                return ResourceManager.GetString("Msg_MergeLocressFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merging uasset. Please wait. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MergeUassetFiles {
            get {
                return ResourceManager.GetString("Msg_MergeUassetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File does not have enough rows to import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NotEnoughRowsToImport {
            get {
                return ResourceManager.GetString("Msg_NotEnoughRowsToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   uexp file not found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NotFoundUexpFile {
            get {
                return ResourceManager.GetString("Msg_NotFoundUexpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No rows selected to delete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NotSelectedRowsToDelete {
            get {
                return ResourceManager.GetString("Msg_NotSelectedRowsToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This version of locres is not supported に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NotSupportedLocresVersion {
            get {
                return ResourceManager.GetString("Msg_NotSupportedLocresVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undefined property type: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NotSupportedProperty {
            get {
                return ResourceManager.GetString("Msg_NotSupportedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This version of uasset is not supported! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NotSupportedUassetVersion {
            get {
                return ResourceManager.GetString("Msg_NotSupportedUassetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving file. Please wait. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SaveFile {
            get {
                return ResourceManager.GetString("Msg_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SearchNotFound {
            get {
                return ResourceManager.GetString("Msg_SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select one row to edit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SelectRowToEdit {
            get {
                return ResourceManager.GetString("Msg_SelectRowToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening file. Please wait. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_StatOpeningFile {
            get {
                return ResourceManager.GetString("Msg_StatOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_TextNotFound {
            get {
                return ResourceManager.GetString("Msg_TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Warning: File was not fully loaded, some text may be missing.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_WarnFileNotReadCompletely {
            get {
                return ResourceManager.GetString("Msg_WarnFileNotReadCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter text to replace... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Placeholder_ReplaceText {
            get {
                return ResourceManager.GetString("Placeholder_ReplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter text to find... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Placeholder_SearchText {
            get {
                return ResourceManager.GetString("Placeholder_SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLI Command List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_CLIList {
            get {
                return ResourceManager.GetString("Title_CLIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Complete {
            get {
                return ResourceManager.GetString("Title_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Confirm {
            get {
                return ResourceManager.GetString("Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export CSV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_ExportCsv {
            get {
                return ResourceManager.GetString("Title_ExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transferring text hashes... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_ForwardingTextHash {
            get {
                return ResourceManager.GetString("Title_ForwardingTextHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import by ID (Slow) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_ImportByIDSlow {
            get {
                return ResourceManager.GetString("Title_ImportByIDSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Importing new rows from CSV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_ImportRowsFromCsv {
            get {
                return ResourceManager.GetString("Title_ImportRowsFromCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import TXT by ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_ImportTextByID {
            get {
                return ResourceManager.GetString("Title_ImportTextByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merging locres... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_MergeLocressFiles {
            get {
                return ResourceManager.GetString("Title_MergeLocressFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merging uasset... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_MergeUassetFiles {
            get {
                return ResourceManager.GetString("Title_MergeUassetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Importing text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_OpenFileDialogTextOrCsv {
            get {
                return ResourceManager.GetString("Title_OpenFileDialogTextOrCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Localization File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_OpenLocalizationFile {
            get {
                return ResourceManager.GetString("Title_OpenLocalizationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Out of range に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_OutOfRange {
            get {
                return ResourceManager.GetString("Title_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_SaveFile {
            get {
                return ResourceManager.GetString("Title_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export TXT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_SaveFileDialogToExportText {
            get {
                return ResourceManager.GetString("Title_SaveFileDialogToExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving file... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_SaveFileEndsWithEllipsis {
            get {
                return ResourceManager.GetString("Title_SaveFileEndsWithEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Results に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_SearchResult {
            get {
                return ResourceManager.GetString("Title_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select localization file(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_SelectLocresMulti {
            get {
                return ResourceManager.GetString("Title_SelectLocresMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening file... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_StatOpeningFile {
            get {
                return ResourceManager.GetString("Title_StatOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select uasset file(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_UassetOrUmap {
            get {
                return ResourceManager.GetString("Title_UassetOrUmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The program will restart if a file is open. Changes will be lost. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTip_WarnRestartIfFileOpened {
            get {
                return ResourceManager.GetString("ToolTip_WarnRestartIfFileOpened", resourceCulture);
            }
        }
    }
}
